# Generated by Django 5.2.dev20240617101926 on 2026-03-27 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('query_text', models.TextField(help_text="User's original prompt")),
                ('output_type', models.CharField(choices=[('CSV', 'CSV'), ('IMAGE', 'Image'), ('PDF', 'PDF'), ('TEXT', 'Text')], max_length=10)),
                ('response_summary', models.TextField(help_text='Short summary or first ~500 chars of the agent response')),
                ('rating', models.CharField(choices=[('positive', 'Positive'), ('negative', 'Negative')], max_length=10)),
                ('comment', models.TextField(blank=True, default='', help_text='Optional free-text feedback from the user')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
